name: Merge Markdown Files

on:
  workflow_dispatch:

jobs:
  merge-md-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find and merge all .md files by natural order
        run: |
          # 使用自然排序，确保数字按预期顺序排列
          find . -name "*.md" | sort -V | while IFS= read -r file; do
            cat "$file" >> merged.md
          done

      - name: Display merged file
        run: cat merged.md

      - name: Commit merged file
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add merged.md
          git commit -m "Merged all markdown files"
          git push
