name: Merge Markdown Files

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  merge-md-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find and merge all .md files by order
        run: |
          # Find all .md files, sort by name, and merge into merged.md if any exist
          md_files=$(find . -name "*.md" | sort)
          if [ -z "$md_files" ]; then
            echo "No markdown files found."
            exit 0
          else
            # Wrap file paths in quotes to handle spaces or special characters
            find . -name "*.md" | sort | while read file; do
              cat "$file" >> merged.md
            done
            echo "Markdown files merged successfully."
          fi

      - name: Display merged file
        run: cat merged.md  # Display merged file content (optional)

      - name: Commit merged file
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add merged.md
          git commit -m "Merged all markdown files"
          git push
